### ISSUE TITLE
kick new - does not finish on windows 8,1 node 4.0.0 (Gulpfile.js is empty)

### ISSUE THREAD

**Issue by HansS** [500tech/angular-kick#33]
C:\Users\Hans\web\angular\20\nir-kaufman\kick-test\app>dir
 Volume in drive C is Windows
 Volume Serial Number is AEB8-B189

 Directory of C:\Users\Hans\web\angular\20\nir-kaufman\kick-test\app

23.09.2015  08:33    <DIR>          .
23.09.2015  08:33    <DIR>          ..
23.09.2015  08:33    <DIR>          app
23.09.2015  08:33               554 config.js
23.09.2015  08:33               175 environments.json
23.09.2015  08:33                76 gitignore
23.09.2015  08:33    <DIR>          gulp
23.09.2015  08:33                 0 Gulpfile.js
23.09.2015  08:33               851 karma.conf.js
23.09.2015  08:33             1 723 package.json
23.09.2015  08:33                 0 README.md
23.09.2015  08:33    <DIR>          test
               7 File(s)          3 379 bytes

**Comment by ilyagelman** [comment]
@HansS Kick 1.0 is not compatible with older versions (not using gulp anymore). You can drop me an email and we can see if I can help you with a migration.

**Comment by HansS** [comment]
Hi Ilya,thank you for the message!I switch to Kick 1.0.2. So far working with no problems!
kind regardsHans

Date: Fri, 25 Sep 2015 03:57:57 -0700
