### ISSUE TITLE
Combine fonts and images loaders into 1 block

### ISSUE THREAD

**Issue by alexilyaev** [500tech/angular-kick#38]
Right now we have:
```js
// Fonts and images
{
  test: /\.(ttf|eot|svg|otf|png)$/,
  loader: 'file'
},
{
  test: /\.(png)$/,
  loader: 'url?mimetype=image/png'
},
{
  test: /\.woff(2)?$/,
  loader: 'url?limit=10000&minetype=application/font-woff'
},
```

I've been using:
```js
// Allow `require`ing image/font files (also when included in CSS)
// Inline assets under 5kb as Base64 data URI, otherwise uses `file-loader`
{
  test: /\.(jpe?g|png|gif|eot|woff2?|ttf|svg)(\?.*)?$/i,
  loaders: [
    'url?limit=5120&name=[path][name].[hash].[ext]'
  ]
}
```

- 5k is the recommended limit for inlining, based on some article.

**Comment by ilyagelman** [comment]
Reminder: we have to check it with bootstrap-sass and font-awesome and see that this is not breaking anything

**Comment by alexilyaev** [comment]
I just checked today the source code of [url-loader](https://github.com/webpack/url-loader/blob/master/index.js), it uses `mime` for each resource by default, which works well, so we don't need to define it ourselves any way.

Also, we use font-awesome in Tradency (from NPM) and it works as well.

**Comment by alexilyaev** [comment]
@ilyagelman Why not combine them as in my example?

**Comment by ilyagelman** [comment]
@alexilyaev Wanted to separate concerns for images and fonts
