### ISSUE TITLE
can't create new application

### ISSUE THREAD

**Issue by i-am-dror** [500tech/angular-kick#67]
kick new [application-name]

/usr/local/lib/node_modules/kick/bin/kick:47
    const answer = prompt(`${message.didYouMean(intention)} ${message.yesNo}`)
                          ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by borisd** [comment]
Hi

I think you are using an old version of node that doesn't support "const",
you need node 4+

On Tue, May 3, 2016 at 1:34 PM, dror <notifications@github.com> wrote:

> kick new [application-name]
>
> /usr/local/lib/node_modules/kick/bin/kick:47
> const answer = prompt(${message.didYouMean(intention)} ${message.yesNo})
> ^
> SyntaxError: Unexpected token ILLEGAL
> at exports.runInThisContext (vm.js:73:16)
> at Module._compile (module.js:443:25)
> at Object.Module._extensions..js (module.js:478:10)
> at Module.load (module.js:355:32)
> at Function.Module._load (module.js:310:12)
> at Function.Module.runMain (module.js:501:10)
> at startup (node.js:129:16)
> at node.js:814:3
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/500tech/angular-kick/issues/67>
>



-- 
- Boris

**Comment by i-am-dror** [comment]
yes, that was it
thanks
